# Generated by Django 5.2 on 2025-05-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='order_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
