# Generated by Django 5.2 on 2025-05-19 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0004_alter_subscription_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='billing_period',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_method',
            field=models.CharField(choices=[('credit', 'Credit Card'), ('ewallet', 'e-Wallet'), ('bank_transfer', 'Bank Transfer'), ('other', 'Other')], max_length=20),
        ),
    ]
